### ISSUE TITLE
yarn.lockとpackage-lock.jsonが混在している

### ISSUE THREAD

**Issue by mizushima1226** [iwkt/react-test#4]
npmとyarnを両方使ってしまった結果２つともできてしまったのだと思います
使用するパッケージマネジャーはどちらか１つに統一し、片方のlockファイルは除去しておくと良いです👍

**Comment by iwkt** [comment]
yarnファイルは削除。ついでに、node_modulesもrmdir 後、npm install しました。
その後のパッケージはnpmに統一したためyarnファイルがなくなりました。
