### ISSUE TITLE
.vscodeについて

### ISSUE THREAD

**Issue by mizushima1226** [iwkt/react-test#6]
課題の要件にある
>Prettier、ESLintの設定がされており、VSCodeで保存時に自動で整形される(.vscodeフォルダもGitHubに含める)

のところですが、お手元の環境で保存時に自動で整形されるでしょうか？
こちらで確認したところ、git cloneしてから.eslintrcを保存した際フォーマットされたのでみくのすけさんの環境で保存した際にフォーマットされていなかったものと予想しています

またはvscodeの設定をユーザー設定として適用しているかもです
ワークスペースに対して設定するように修正する必要があります〜💡

**Comment by iwkt** [comment]
前回、.vscodeフォルダがgitに含まれておりませんでした。今回gitに反映するようフォルダを移動しました。これで適用されているように思います。
といいつつもあまり自信がありません。的外れな回答でしたらごめんなさい。

参考元：
https://maku.blog/p/tfq2cnw/

**Comment by mizushima1226** [comment]
Goodです！👍
