### ISSUE TITLE
Cannot find module babel-eslintについて

### ISSUE THREAD

**Issue by mizushima1226** [iwkt/react-test#7]
[こちら](https://qiita.com/harker/items/b66ad0ccc74e28fb6315)を参照したようですが、記事が少し古く、LGTMも２つしかついていないのでもしかしたら良い記事ではなかったかもしれません。

自分も最初の頃は設定系のいろんな記事に翻弄されて非常に苦労した記憶があります😇

[公式ドキュメント](https://eslint.org/docs/user-guide/getting-started)になりますが、一番信頼できるドキュメントだと思います
公式ドキュメントをもとにわからない箇所は適宜ググるのがよいかと！

ちなみにeslintのメジャーバージョンも2021/10に上がっていたようです💡
https://github.com/eslint/eslint/releases/tag/v8.0.0

create-react-appからeslintの設定まで試してみましたがうまくいくこと確認できております〜

**Comment by iwkt** [comment]
ご提示いただいた公式をみてインストールしたところ同様のエラーが出なくなりました。

上手く行ったもののいくつか疑問がありますので記載いたします。

1. package.jsonに"plugin:prettier/recommended"が追加されていました。
こちらは.eslint.jsonで反映できると考えこの一文を削除しました。
このような理解でよろしいでしょうか？```
"eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
      "plugin:prettier/recommended"　//.eslint.jsonにあるので不要と思い削除した
    ]
  }
```

**Comment by iwkt** [comment]
ご提示いただいた公式をみてインストールしたところ同様のエラーが出なくなりました。

**Comment by mizushima1226** [comment]
👍
